version: '2'
volumes:
  db_data:
    driver: local
services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - 8001:80
  app:
    image: lorisleiva/laravel-docker:7.3
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    tty: true
    stdin_open: true